version: '3'

services:
  postgres:
      image: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: thoth
      ports:
        - "5432:5432"
      volumes:
        - ./../postgres/:/docker-entrypoint-initdb.d/
